### ISSUE TITLE
Mail alerting

### ISSUE THREAD

**Issue by anaaman** [ksator/junos_monitoring_with_healthbot#2]
Is the any way to send an alert via SMTP ?

**Comment by subodh100** [comment]
HealthBot currently support following notification mechanism :
   - Slack Channel
   - Web Hook
   - Kafka Publish

SMTP is in pipeline and will be implemented soon.

HealthBot also has a Reporting feature which can be used to generate a reports for a given period (once, or repeated with a configured frequency). These reports can be sent over mails.

To get more timely response to your question related to HealthBot, you can start posting questions on https://juniperengnet.slack.com/messages/CEU45D0SD 

Thanks
Subodh

**Comment by anaaman** [comment]
Hi Subodh,
Thanks. How can I gain access to Juniper slack?

Thanks

**Comment by ksator** [comment]
this feature is now released (HB 2.1)
